### ISSUE TITLE
bug: Division and Multiplication don't work

### ISSUE THREAD

**Issue by democat3457** [xarkenz/mars-red#5]
When using a `div` instruction, the hi and lo registers don't get assigned values.

Minimum reproducible example:
```asm
.text
li $t0, 7
li $t1, 3
div $t0, $t1
mfhi $t3
mflo $t2
```
<img width="389" alt="image" src="https://github.com/xarkenz/mars-red/assets/32407067/86eb6aa3-75c8-4c74-ace6-3415d6b2f341">

EDIT: Same thing happens when you replace `div` with `mul`

**Comment by xarkenz** [comment]
Fixed in the latest commit. The problem was that `RegisterFile.updateRegister()` would do nothing for register numbers >= 32, but numbers 32, 33, and 34 are used internally for `pc`, `hi`, and `lo` respectively, meaning they could not be updated that way. Now, the method will accept the three internal numbers.
